apiVersion: apps/v1 
kind: Deployment
metadata:
  name: node-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-example
  template:
    metadata:
      labels:
        app: node-example
    spec:
      containers:
      - name: node-example
        image: 13wrightd/resumearch
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
        volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
        - name: mypd
          mountPath: "/tmp/persistent"
        - name: nfs-data
          mountPath: "/nfs/"
      volumes:
      - name: shared-data
        emptyDir: {}
      - name: mypd
        persistentVolumeClaim:
          claimName: myclaim
      - name: nfs-data
        persistentVolumeClaim:
          claimName: nfsclaim
