apiVersion: apps/v1 
kind: Deployment
metadata:
  name: node-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-example
  template:
    metadata:
      labels:
        app: node-example
    spec:
      containers:
      - name: node-example
        image: 13wrightd/resumearch:2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
        volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
      volumes:
      - name: shared-data
        emptyDir: {}
